# Site settings
title: "Name"
subtitle: "Subtitle"
email: youremail@gmail.com
url: 
description: "This is My Page"
keywords: "keywords, keywords2"
meta_author: 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d1d1cb #80B3FF
  primary-rgb: "209,209,203" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-rgb: "44,62,80"
  secondary-dark: 233140 #A2122F
  tertiary: 800080
  tertiary-rgb: "128,0,128"

# Footer settings
footer:
  copyright: Bootstrap theme
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: 
  - title: tableau
    url: 
  - title: kaggle
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: City
  - line: Country

# Credits content
credits: ': This webpage is based on Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
